---
- name: "Install calicoctl"
  copy:
    src: "{{ download.dest }}/calico/{{ calico.version }}/{%- if ansible_architecture == 'x86_64' -%}amd64{%- else -%}arm64{%- endif -%}/calicoctl-linux-{%- if ansible_architecture == 'x86_64' -%}amd64{%- else -%}arm64{%- endif -%}"
    dest: "/usr/local/bin/calicoctl"
    mode: 0750
    seuser: system_u
    setype: bin_t
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['master'] }}"
  tags: calicoctl

- name: "Create calico directory"
  file:
    path: "/etc/calico"
    state: directory
    seuser: system_u
    setype: etc_t
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['master'] }}"
  tags: calicoctl

- name: "Copy calicoctl config"
  template:
    src: "calicoctl.cfg.j2"
    dest: "/etc/calico/calicoctl.cfg"
    seuser: system_u
    setype: etc_t
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['master'] }}"
  tags: calicoctl
