- name: restart sshd
  systemd:
    name: "{{ 'sshd' if ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky', 'TencentOS'] else 'ssh' }}"
    state: restarted
    enabled: yes
    masked: false
- name: restart chrony
  systemd:
    name: chronyd
    state: restarted
    enabled: yes
    masked: false
- name: restart systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: yes
    masked: false
- name: restart systemd-journald
  systemd:
    name: systemd-journald
    state: restarted
    enabled: yes
    masked: false