---
- name: "Set hostname"
  hostname:
    name: "{{ hostname|quote }}"
    use: systemd
  tags: hostname

- name: "Set env"
  copy:
    src: "ipenv.sh"
    dest: "/etc/profile.d/"
    seuser: system_u
    setype: bin_t
  tags: os_env

- name: "Set timezone"
  community.general.timezone:
    name: Asia/Shanghai
  tags: timezone

- name: "Install chrony"
  package:
    name: chrony
    state: present
  tags: ntp

- name: "Generate NTP configuration file"
  template:
    src: "chrony.conf.j2"
    dest: "/etc/chrony.conf"
  when:
    - ntp.manage_config
  tags: ntp

- name: Ensure NTP service is started and enabled
  systemd:
    name: chronyd
    state: restarted
    enabled: yes
    masked: false
  tags: ntp

- name: "Disable swap"
  shell: swapoff -a
  tags: swap

- name: "Remove swapfile from /etc/fstab"
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none
  tags: swap

- name: "Enable SELinux"
  selinux:
    policy: targeted
    state: enforcing
  when:
    - ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky', 'TencentOS']
  tags: selinux

- name: "Get firewalld is installed"
  command: whereis firewalld
  register: firewalld_state
  tags: firewalld

- name: "Stop firewalld"
  when: "'/usr/sbin/firewalld' in firewalld_state.stdout"
  systemd:
    name: firewalld
    enabled: no
    masked: false
    state: stopped
  tags: firewalld

- name: "Set ssh"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "UseDNS", line: "UseDNS no" }
    - { regexp: "ClientAliveInterval", line: "ClientAliveInterval 600" }
    - { regexp: "ClientAliveCountMax", line: "ClientAliveCountMax 2" }
    - { regexp: "AddressFamily", line: "AddressFamily inet" }
    - { regexp: "PermitRootLogin", line: "PermitRootLogin yes" }
    - { regexp: "PermitEmptyPasswords", line: "PermitEmptyPasswords no" }
    - { regexp: "PasswordAuthentication", line: "PasswordAuthentication no" }
  notify:
    - restart sshd
  tags: sshd

- name: "Set limits"
  pam_limits:
    dest: "/etc/security/limits.conf"
    domain: '{{ item.limit_domain }}'
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - { limit_domain: 'root',limit_type: 'soft',limit_item: 'nofile', value: '655360' }
    - { limit_domain: 'root',limit_type: 'hard',limit_item: 'nofile', value: '655360' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'nproc', value: '655360' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'nproc', value: '655360' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'nofile', value: '655360' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'nofile', value: '655360' }
  tags: limits

- name: "Set systemd limits"
  lineinfile:
    dest: "/etc/systemd/system.conf"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {line: 'DefaultLimitNOFILE=65535' }
    - {line: 'DefaultLimitNPROC=65535' }
  tags: limits

- name: "Modify sysctl"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - {name: 'kernel.sysrq',value: '1' }
    - {name: 'vm.swappiness ',value: ' 0' }
    - {name: 'net.ipv4.ip_forward',value: '1' }
    - {name: 'net.ipv4.neigh.default.gc_stale_time',value: '120' }
    - {name: 'net.ipv4.conf.all.rp_filter',value: '0' }
    - {name: 'net.ipv4.conf.default.rp_filter',value: '0' }
    - {name: 'net.ipv4.conf.default.arp_announce ',value: ' 2' }
    - {name: 'net.ipv4.conf.lo.arp_announce',value: '2' }
    - {name: 'net.ipv4.conf.all.arp_announce',value: '2' }
    - {name: 'net.ipv4.tcp_max_tw_buckets',value: '5000' }
    - {name: 'net.ipv4.tcp_syncookies ',value: ' 1' }
    - {name: 'net.ipv4.tcp_max_syn_backlog ',value: ' 1024' }
    - {name: 'net.ipv4.tcp_synack_retries ',value: ' 2' }
    - {name: 'net.ipv4.tcp_fin_timeout',value: '30' }
    - {name: 'net.ipv4.tcp_keepalive_time',value: '600' }
    - {name: 'net.ipv4.tcp_keepalive_intvl',value: '30' }
    - {name: 'net.ipv4.tcp_keepalive_probes',value: '10' }
    - {name: 'net.ipv4.ip_local_port_range',value: '20000 60999' }
  tags: sysctl

- name: "Config systemd-journald"
  file:
    path: "/var/log/journal"
    owner: root
    group: systemd-journal
    mode: 2775
    state: directory
  notify:
    - restart systemd-journald
  when:
    - ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky', 'TencentOS']
  tags: journal

- name: "Install base application"
  package:
    name:
      - vim
      - mtr
      - tar
      - curl
      - lsof
      - unzip
      - lrzsz
      - rsync
      - bash-completion
    state: present
  tags: install_app

- name: "Install base application"
  package:
    name:
      - nmap-ncat
      - yum-utils
      - nfs-utils
      - iproute
    state: present
  when:
    - ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky', 'TencentOS']
  tags: install_app

- name: "Install base application"
  package:
    name:
      - nmap
      - nmap-common
      - nfs-common
      - iproute2
    state: present
  when:
    - ansible_os_family in ["Debian"]
  tags: install_app
