name: Docker Image && Kubernetes Release

on:
  push:
    branches:
      - main
    paths:
      - 'group_vars/all.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'group_vars/all.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Run script
      run: |
        python generate.py

    - name: Sync Images
      uses: hhyasdf/image-sync-action@v1.1
      with:
        auth_file: ./auth.yaml
        images_file: ./images.yaml
        version: latest
        arch: amd64, arm64
        proc: 6
      env:
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        DKH_USERNAME: ${{ secrets.DKH_USERNAME }}
        DKH_PASSWORD: ${{ secrets.DKH_PASSWORD }}
