name: Docker Image Syncer

on:
  push:
    branches:
      - main
    paths:
      - 'group_vars/all.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'group_vars/all.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Run script
      run: |
        python generate.py

    - name: Sync Images
      env:
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        DKH_USERNAME: ${{ secrets.DKH_USERNAME }}
        DKH_PASSWORD: ${{ secrets.DKH_PASSWORD }}
      run: |
        target_tag=$(curl --silent "https://api.github.com/repos/AliyunContainerService/image-syncer/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        wget --quiet https://github.com/AliyunContainerService/image-syncer/releases/download/"${target_tag}"/image-syncer-"${target_tag}"-linux-amd64.tar.gz
        tar -xvf image-syncer-"${target_tag}"-linux-amd64.tar.gz
        ./image-syncer --auth=./auth.yaml --images=./images.yaml --arch=amd64 --arch=arm64 --os=linux --proc=6 --retries=3
